FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY Services.IdentityService.csproj ./
RUN dotnet restore Services.IdentityService.csproj
COPY . .
WORKDIR /src
RUN dotnet publish Services.IdentityService.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80
ENTRYPOINT ["dotnet", "Services.IdentityService.dll"]