# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'catalogservice'
    static_configs:
      - targets: ['catalogservice:8080']  # /metrics endpoint

  - job_name: 'orderservice'
    static_configs:
      - targets: ['orderservice:8080']

  # Thêm service khác nếu cần